{"is_source_file": true, "format": "Groovy (Gradle build script)", "description": "This is a Gradle build configuration script for an Android application project, specifying plugins, Android SDK versions, build features, default configurations, build types, and dependencies.", "external_files": [], "external_methods": [], "published": [], "classes": [], "methods": [], "calls": ["getDefaultProguardFile"], "search-terms": ["build.gradle", "com.android.application", "namespace", "compileSdk", "buildFeatures", "defaultConfig", "compileOptions", "buildTypes", "dependencies"], "state": 2, "file_id": 18, "knowledge_revision": 46, "git_revision": "", "hash": "06a60e0a4dff0bcc275e4c98683d3c31", "format-version": 4, "code-base-name": "default", "filename": "recipehub_main_container/app/build.gradle", "revision_history": [{"46": ""}]}